# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-12 12:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, default=datetime.datetime(2016, 4, 12, 12, 37, 52, 480000, tzinfo=utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
