# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-12 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20160412_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='time',
            field=models.IntegerField(),
        ),
    ]
