# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-21 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20160412_2104'),
        ('movie', '0002_auto_20160421_0718'),
    ]

    operations = [
    ]
